[package]
name = "logos-store-aletheia"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
logos-core = { path = "../logos-core" }
aletheiadb = { git = "https://github.com/madmax983/AletheiaDB.git", branch = "trunk" }
shh = "1.0.1"

[dev-dependencies]
loom = "0.7.2"
proptest = "1.10.0"
tempfile = "3.27.0"
