[package]
name = "logos-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
blake3 = "1.8.3"
chrono = { version = "0.4.42", default-features = true, features = ["clock"] }
logos-core = { path = "../logos-core" }
logos-import = { path = "../logos-import" }
logos-reporting = { path = "../logos-reporting" }
logos-store-aletheia = { path = "../logos-store-aletheia" }
comfy-table = "7.1"
polars = { version = "0.46.0", features = ["parquet"] }
