[package]
name = "logos-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
logos-core = { path = "../logos-core" }
logos-import = { path = "../logos-import" }
logos-reporting = { path = "../logos-reporting" }
logos-store-aletheia = { path = "../logos-store-aletheia" }
