//! Debt Optimizer Simulator.
//!
//! A module to simulate and compare different debt payoff strategies
//! ("Snowball" vs "Avalanche").

/// Represents a single debt obligation.
#[derive(Debug, Clone, PartialEq)]
pub struct Debt {
    /// The name or identifier of the debt.
    pub name: String,
    /// The outstanding principal balance in cents.
    pub balance_cents: i64,
    /// The annual interest rate as a percentage (e.g., 5.5 for 5.5%).
    pub interest_rate_pct: f64,
    /// The minimum required monthly payment in cents.
    pub min_payment_cents: i64,
}

impl Debt {
    /// Creates a new `Debt`.
    #[must_use]
    pub fn new(name: &str, balance_cents: i64, interest_rate_pct: f64, min_payment_cents: i64) -> Self {
        Self {
            name: name.to_owned(),
            balance_cents,
            interest_rate_pct,
            min_payment_cents,
        }
    }

    /// Calculates the monthly interest generated by this debt.
    #[must_use]
    pub fn monthly_interest_cents(&self) -> i64 {
        if self.balance_cents <= 0 {
            return 0;
        }
        let monthly_rate = self.interest_rate_pct / 100.0 / 12.0;
        #[allow(clippy::cast_precision_loss)]
        let balance_f64 = self.balance_cents as f64;
        let interest = balance_f64 * monthly_rate;
        #[allow(clippy::cast_possible_truncation)]
        let interest_cents = interest.round() as i64;
        interest_cents
    }
}

/// The strategy to use when allocating extra funds for debt payoff.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PayoffStrategy {
    /// Avalanche: Target the highest interest rate first.
    /// Mathematically optimal for minimizing total interest paid.
    Avalanche,
    /// Snowball: Target the smallest balance first.
    /// Psychologically optimal for quick wins.
    Snowball,
}

/// The result of a debt payoff simulation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PayoffResult {
    /// The total number of months it took to become debt-free.
    pub months_to_payoff: u32,
    /// The total amount of interest paid across all debts in cents.
    pub total_interest_paid_cents: i64,
}

/// A projector to simulate debt payoff over time.
#[derive(Debug, Clone)]
pub struct DebtOptimizer {
    debts: Vec<Debt>,
    monthly_budget_cents: i64,
}

impl DebtOptimizer {
    /// Creates a new `DebtOptimizer`.
    ///
    /// The `monthly_budget_cents` must be at least the sum of all minimum payments,
    /// otherwise the simulation would never complete.
    #[must_use]
    pub const fn new(debts: Vec<Debt>, monthly_budget_cents: i64) -> Self {
        Self {
            debts,
            monthly_budget_cents,
        }
    }

    /// Runs the simulation using the specified strategy.
    #[must_use]
    pub fn simulate(&self, strategy: PayoffStrategy) -> PayoffResult {
        let mut current_debts = self.debts.clone();
        let mut months = 0;
        let mut total_interest_paid = 0;

        // Ensure we don't loop forever if budget is too small or balances just grow
        let max_months = 1200; // 100 years

        while !current_debts.is_empty() && months < max_months {
            months += 1;

            // 1. Calculate and apply monthly interest for all debts
            for debt in &mut current_debts {
                let interest = debt.monthly_interest_cents();
                total_interest_paid += interest;
                debt.balance_cents += interest;
            }

            // 2. Sort debts according to the strategy for extra payment targeting
            match strategy {
                PayoffStrategy::Avalanche => {
                    // Sort by interest rate descending, then balance descending as tie-breaker
                    current_debts.sort_unstable_by(|a, b| {
                        b.interest_rate_pct
                            .partial_cmp(&a.interest_rate_pct)
                            .unwrap_or(std::cmp::Ordering::Equal)
                            .then_with(|| b.balance_cents.cmp(&a.balance_cents))
                    });
                }
                PayoffStrategy::Snowball => {
                    // Sort by balance ascending, then interest rate descending as tie-breaker
                    current_debts.sort_unstable_by(|a, b| {
                        a.balance_cents
                            .cmp(&b.balance_cents)
                            .then_with(|| {
                                b.interest_rate_pct
                                    .partial_cmp(&a.interest_rate_pct)
                                    .unwrap_or(std::cmp::Ordering::Equal)
                            })
                    });
                }
            }

            // 3. Make minimum payments
            let mut remaining_budget = self.monthly_budget_cents;

            // First pass: everyone gets their minimum payment (or the remaining balance if less)
            for debt in &mut current_debts {
                if remaining_budget <= 0 { break; }

                let payment = std::cmp::min(debt.balance_cents, debt.min_payment_cents);
                let payment = std::cmp::min(payment, remaining_budget);

                debt.balance_cents -= payment;
                remaining_budget -= payment;
            }

            // 4. Apply remaining budget as extra payments
            for debt in &mut current_debts {
                if remaining_budget <= 0 { break; }

                let extra_payment = std::cmp::min(debt.balance_cents, remaining_budget);
                debt.balance_cents -= extra_payment;
                remaining_budget -= extra_payment;
            }

            // 5. Remove paid off debts
            current_debts.retain(|d| d.balance_cents > 0);
        }

        PayoffResult {
            months_to_payoff: months,
            total_interest_paid_cents: total_interest_paid,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_debt_interest_calculation() {
        let debt = Debt::new("Test", 1000_00, 12.0, 50_00); // 12% annual = 1% monthly
        assert_eq!(debt.monthly_interest_cents(), 10_00); // 1% of 1000 = 10
    }

    #[test]
    fn test_avalanche_vs_snowball() {
        // Setup a classic scenario where Avalanche beats Snowball mathematically
        // Debt 1: Small balance, low interest
        let cc1 = Debt::new("Small CC", 1000_00, 5.0, 25_00);
        // Debt 2: Large balance, high interest
        let cc2 = Debt::new("Large CC", 5000_00, 20.0, 100_00);
        // Debt 3: Medium balance, medium interest
        let cc3 = Debt::new("Car Loan", 3000_00, 10.0, 150_00);

        let debts = vec![cc1, cc2, cc3];
        // Total minimums = 275. Budget = 500 (225 extra per month)
        let optimizer = DebtOptimizer::new(debts, 500_00);

        let snowball_result = optimizer.simulate(PayoffStrategy::Snowball);
        let avalanche_result = optimizer.simulate(PayoffStrategy::Avalanche);

        // Both should pay off eventually
        assert!(snowball_result.months_to_payoff > 0);
        assert!(avalanche_result.months_to_payoff > 0);

        // Avalanche MUST pay less total interest than Snowball
        assert!(
            avalanche_result.total_interest_paid_cents < snowball_result.total_interest_paid_cents,
            "Avalanche should result in less total interest paid. Avalanche: {}, Snowball: {}",
            avalanche_result.total_interest_paid_cents,
            snowball_result.total_interest_paid_cents
        );
    }

    #[test]
    fn test_budget_too_small() {
        // If budget is less than interest generated, it loops to max_months
        let cc1 = Debt::new("Giant CC", 100000_00, 24.0, 10_00); // $2000/mo interest
        let optimizer = DebtOptimizer::new(vec![cc1], 100_00); // Paying $100/mo

        let result = optimizer.simulate(PayoffStrategy::Avalanche);
        assert_eq!(result.months_to_payoff, 1200);
    }
}
