//! Portfolio Rebalancer
//!
//! A simulation tool to calculate the exact buy and sell orders needed
//! to realign an investment portfolio back to its target asset allocation.
//! This uses integer basis points (1/100th of a percent) for exact allocation
//! targets (e.g., 5000 bps = 50.00%).

/// Represents an individual asset class or ticker in the portfolio.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Asset {
    /// Identifier for the asset (e.g., "VTI", "BND", "US Stocks").
    pub name: String,
    /// The current value of this asset in the portfolio in cents.
    pub current_value_cents: i64,
    /// The desired target allocation in basis points (0 to 10000).
    /// For example, 6000 = 60%.
    pub target_allocation_bps: u32,
}

/// Represents the action required to bring an asset to its target allocation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RebalanceAction {
    /// Buy more of the asset by the specified amount in cents.
    Buy { amount_cents: i64 },
    /// Sell some of the asset by the specified amount in cents.
    Sell { amount_cents: i64 },
    /// No action is needed; the asset is perfectly allocated.
    Hold,
}

/// The result of running a rebalance simulation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RebalancePlan {
    /// The total value of the portfolio in cents.
    pub total_portfolio_value_cents: i64,
    /// The specific actions to take for each asset, mapped by asset name.
    pub actions: std::collections::HashMap<String, RebalanceAction>,
    /// The total amount of cash needed to execute all buys (in cents).
    /// In a closed system, this should closely match the total amount generated by sells,
    /// modulo rounding differences.
    pub total_buy_volume_cents: i64,
    /// The total amount of cash generated by executing all sells (in cents).
    pub total_sell_volume_cents: i64,
}

/// A projector to simulate bringing a portfolio back to its target allocation.
#[derive(Debug, Clone, Default)]
pub struct PortfolioRebalancer {
    assets: Vec<Asset>,
}

impl PortfolioRebalancer {
    /// Creates a new, empty `PortfolioRebalancer`.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Adds an asset with its current value and target allocation.
    ///
    /// ## Panics
    /// Panics if the `target_allocation_bps` exceeds 10000 (100%).
    pub fn add_asset(&mut self, asset: Asset) {
        assert!(
            asset.target_allocation_bps <= 10000,
            "Target allocation cannot exceed 10000 basis points (100%)"
        );
        self.assets.push(asset);
    }

    /// Calculates the required actions to rebalance the portfolio.
    ///
    /// If the total target allocation of all assets is less than 10000 (100%),
    /// the remaining percentage is implicitly considered "unallocated cash" that
    /// requires no action.
    ///
    /// ## Panics
    ///
    /// If the total target allocation exceeds 10000, this will panic to prevent
    /// generating impossible financial plans.
    #[must_use]
    pub fn calculate_rebalance(&self) -> RebalancePlan {
        let total_value: i64 = self.assets.iter().map(|a| a.current_value_cents).sum();

        let total_bps: u32 = self.assets.iter().map(|a| a.target_allocation_bps).sum();
        assert!(
            total_bps <= 10000,
            "Total target allocation across all assets exceeds 10000 basis points (100%)"
        );

        let mut actions = std::collections::HashMap::new();
        let mut total_buy = 0;
        let mut total_sell = 0;

        for asset in &self.assets {
            // Calculate target value: (total_value * target_bps) / 10000
            // We use i128 to prevent overflow during multiplication before division
            let target_value_cents =
                (i128::from(total_value) * i128::from(asset.target_allocation_bps)) / 10000;

            #[allow(clippy::cast_possible_truncation)]
            let target_value_cents = target_value_cents as i64;

            let difference = target_value_cents - asset.current_value_cents;

            let action = match difference.cmp(&0) {
                std::cmp::Ordering::Greater => {
                    total_buy += difference;
                    RebalanceAction::Buy {
                        amount_cents: difference,
                    }
                }
                std::cmp::Ordering::Less => {
                    let sell_amount = difference.abs();
                    total_sell += sell_amount;
                    RebalanceAction::Sell {
                        amount_cents: sell_amount,
                    }
                }
                std::cmp::Ordering::Equal => RebalanceAction::Hold,
            };

            actions.insert(asset.name.clone(), action);
        }

        RebalancePlan {
            total_portfolio_value_cents: total_value,
            actions,
            total_buy_volume_cents: total_buy,
            total_sell_volume_cents: total_sell,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_perfect_portfolio_holds() {
        let mut rebalancer = PortfolioRebalancer::new();
        rebalancer.add_asset(Asset {
            name: "VTI".to_string(),
            current_value_cents: 6000,
            target_allocation_bps: 6000, // 60%
        });
        rebalancer.add_asset(Asset {
            name: "VXUS".to_string(),
            current_value_cents: 4000,
            target_allocation_bps: 4000, // 40%
        });

        let plan = rebalancer.calculate_rebalance();

        assert_eq!(plan.total_portfolio_value_cents, 10000);
        assert_eq!(plan.actions.get("VTI").unwrap(), &RebalanceAction::Hold);
        assert_eq!(plan.actions.get("VXUS").unwrap(), &RebalanceAction::Hold);
        assert_eq!(plan.total_buy_volume_cents, 0);
        assert_eq!(plan.total_sell_volume_cents, 0);
    }

    #[test]
    fn test_basic_rebalance() {
        let mut rebalancer = PortfolioRebalancer::new();
        // Portfolio drifted: VTI is at 70%, VXUS is at 30%
        rebalancer.add_asset(Asset {
            name: "VTI".to_string(),
            current_value_cents: 7000,
            target_allocation_bps: 6000, // Target 60%
        });
        rebalancer.add_asset(Asset {
            name: "VXUS".to_string(),
            current_value_cents: 3000,
            target_allocation_bps: 4000, // Target 40%
        });

        let plan = rebalancer.calculate_rebalance();

        assert_eq!(plan.total_portfolio_value_cents, 10000);

        // VTI target is 6000, current is 7000. Sell 1000.
        assert_eq!(
            plan.actions.get("VTI").unwrap(),
            &RebalanceAction::Sell { amount_cents: 1000 }
        );

        // VXUS target is 4000, current is 3000. Buy 1000.
        assert_eq!(
            plan.actions.get("VXUS").unwrap(),
            &RebalanceAction::Buy { amount_cents: 1000 }
        );

        assert_eq!(plan.total_buy_volume_cents, 1000);
        assert_eq!(plan.total_sell_volume_cents, 1000);
    }

    #[test]
    fn test_zero_allocation_sells_all() {
        let mut rebalancer = PortfolioRebalancer::new();
        rebalancer.add_asset(Asset {
            name: "Old Stock".to_string(),
            current_value_cents: 5000,
            target_allocation_bps: 0, // Target 0%
        });
        rebalancer.add_asset(Asset {
            name: "New Stock".to_string(),
            current_value_cents: 5000,
            target_allocation_bps: 10000, // Target 100%
        });

        let plan = rebalancer.calculate_rebalance();

        assert_eq!(
            plan.actions.get("Old Stock").unwrap(),
            &RebalanceAction::Sell { amount_cents: 5000 }
        );
        assert_eq!(
            plan.actions.get("New Stock").unwrap(),
            &RebalanceAction::Buy { amount_cents: 5000 }
        );
    }

    #[test]
    #[should_panic(expected = "Target allocation cannot exceed 10000 basis points")]
    fn test_add_asset_panics_on_invalid_bps() {
        let mut rebalancer = PortfolioRebalancer::new();
        rebalancer.add_asset(Asset {
            name: "Impossible".to_string(),
            current_value_cents: 1000,
            target_allocation_bps: 10001, // 100.01%
        });
    }

    #[test]
    #[should_panic(
        expected = "Total target allocation across all assets exceeds 10000 basis points"
    )]
    fn test_calculate_panics_on_over_allocation() {
        let mut rebalancer = PortfolioRebalancer::new();
        rebalancer.add_asset(Asset {
            name: "A".to_string(),
            current_value_cents: 100,
            target_allocation_bps: 6000,
        });
        rebalancer.add_asset(Asset {
            name: "B".to_string(),
            current_value_cents: 100,
            target_allocation_bps: 5000, // Total = 11000
        });

        let _ = rebalancer.calculate_rebalance();
    }
}
