[package]
name = "logos-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
logos-store-pg = { path = "../logos-store-pg" }
logos-core = { path = "../logos-core" }
logos-runtime = { path = "../logos-runtime" }
comfy-table = "7.2.2"
crossterm = "0.29.0"
ratatui = "0.29.0"
