//! # Scenario-Based Budget Modeling
//!
//! Provides the mathematical models for converting volatile Restricted Stock Units (RSUs)
//! into stable monthly budgets. Because stock prices fluctuate, this module enforces
//! a "Bear Case First" planning model, guaranteeing that fixed commitments are always
//! covered by the worst-case price scenario.

use logos_core::{HaircutTierTable, forecast_value_cents};

/// Identifies the market condition scenario for a given projection.
///
/// ## Examples
///
/// ```
/// use logos_reporting::ScenarioKey;
///
/// let scenario = ScenarioKey::Base;
/// assert_eq!(scenario, ScenarioKey::Base);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScenarioKey {
    /// A conservative, pessimistic price target (the baseline).
    Bear,
    /// The expected, likely price target.
    Base,
    /// An optimistic price target.
    Bull,
}

/// A strictly monotonic set of price targets (Bear <= Base <= Bull) used for simulation.
///
/// Ensures the integrity of the Bear-Case First budget model by enforcing price boundaries.
///
/// ## Examples
///
/// ```
/// use logos_reporting::ScenarioPriceInputs;
///
/// let inputs = ScenarioPriceInputs::new(100_00, 150_00, 200_00).expect("should succeed");
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ScenarioPriceInputs {
    bear: i64,
    base: i64,
    bull: i64,
}

impl ScenarioPriceInputs {
    /// Creates a monotonic bear/base/bull scenario price set.
    ///
    /// The prices must strictly follow `bear_price_cents <= base_price_cents <= bull_price_cents`.
    ///
    /// # Errors
    ///
    /// Returns an error when any price is non-positive or when
    /// the monotonic ordering rule is violated.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::ScenarioPriceInputs;
    ///
    /// let prices = ScenarioPriceInputs::new(50_00, 100_00, 150_00).expect("should succeed");
    /// ```
    pub fn new(
        bear_price_cents: i64,
        base_price_cents: i64,
        bull_price_cents: i64,
    ) -> Result<Self, String> {
        if bear_price_cents <= 0 || base_price_cents <= 0 || bull_price_cents <= 0 {
            return Err("scenario prices must be positive".to_owned());
        }
        if !(bear_price_cents <= base_price_cents && base_price_cents <= bull_price_cents) {
            return Err("scenario prices must satisfy bear <= base <= bull".to_owned());
        }
        Ok(Self {
            bear: bear_price_cents,
            base: base_price_cents,
            bull: bull_price_cents,
        })
    }
}

/// The projected outcome of a specific market condition on a monthly budget.
///
/// Captures how volatile income scales and dictates the automatic division of
/// cash into required minimums versus optional surplus sweeps.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ScenarioBudgetProjection {
    scenario: ScenarioKey,
    monthly_income_cents: i64,
    surplus_cents: i64,
    reserve_sweep_cents: i64,
    investing_sweep_cents: i64,
    available_after_sweeps_cents: i64,
}

impl ScenarioBudgetProjection {
    /// The specific market condition context this projection operates under.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan, ScenarioKey};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// assert_eq!(plan.base().unwrap().scenario(), ScenarioKey::Base);
    /// ```
    #[must_use]
    pub const fn scenario(&self) -> ScenarioKey {
        self.scenario
    }

    /// The net disposable monthly cash generated by selling the vested shares at the scenario price,
    /// after applying default haircut estimates for taxes.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// assert_eq!(plan.base().unwrap().monthly_income_cents(), 11250_00);
    /// ```
    #[must_use]
    pub const fn monthly_income_cents(&self) -> i64 {
        self.monthly_income_cents
    }

    /// The discretionary cash generated above the conservative `Bear` baseline budget,
    /// representing funds that are available for sweeping into savings or optional goals.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// // Base income ($11,250) - Bear baseline ($7,500) = $3,750
    /// assert_eq!(plan.base().unwrap().surplus_cents(), 3750_00);
    /// ```
    #[must_use]
    pub const fn surplus_cents(&self) -> i64 {
        self.surplus_cents
    }

    /// The absolute cash value derived from applying the reserve sweep percentage
    /// against the `surplus_cents`. Used to automatically build emergency funds during good months.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// // 10% reserve sweep of a $3,750 surplus
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// assert_eq!(plan.base().unwrap().reserve_sweep_cents(), 375_00);
    /// ```
    #[must_use]
    pub const fn reserve_sweep_cents(&self) -> i64 {
        self.reserve_sweep_cents
    }

    /// The absolute cash value derived from applying the investing sweep percentage
    /// against the `surplus_cents`. Drives automated dollar-cost averaging models.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// // 20% investing sweep of a $3,750 surplus
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// assert_eq!(plan.base().unwrap().investing_sweep_cents(), 750_00);
    /// ```
    #[must_use]
    pub const fn investing_sweep_cents(&self) -> i64 {
        self.investing_sweep_cents
    }

    /// The final, unallocated cash pool available after deducting the conservative budget baseline
    /// and routing the designated percentages into the reserve and investing sweeps.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// // Base income $11,250 - (Reserve $375 + Investing $750) = $10,125
    /// assert_eq!(plan.base().unwrap().available_after_sweeps_cents(), 10125_00);
    /// ```
    #[must_use]
    pub const fn available_after_sweeps_cents(&self) -> i64 {
        self.available_after_sweeps_cents
    }
}

/// The required parameters to project an RSU-backed monthly budget.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RsuBudgetPlanInput {
    quarterly_units: u32,
    days_to_vest: u16,
    scenario_prices: ScenarioPriceInputs,
    fixed_commitments_cents: i64,
    reserve_sweep_pct: u8,
    investing_sweep_pct: u8,
}

impl RsuBudgetPlanInput {
    /// Creates a validated RSU budget planning input payload.
    ///
    /// # Errors
    ///
    /// Returns an error when units are zero, fixed commitments are negative, or
    /// reserve/investing sweeps exceed 100% combined.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs};
    ///
    /// let prices = ScenarioPriceInputs::new(50_00, 100_00, 150_00).expect("should succeed");
    /// // 300 units, 0 days to vest, $5,000 fixed commitments, 10% reserve sweep, 20% investing sweep
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 5000_00, 10, 20).expect("should succeed");
    /// ```
    pub fn new(
        quarterly_units: u32,
        days_to_vest: u16,
        scenario_prices: ScenarioPriceInputs,
        fixed_commitments_cents: i64,
        reserve_sweep_pct: u8,
        investing_sweep_pct: u8,
    ) -> Result<Self, String> {
        if quarterly_units == 0 {
            return Err("quarterly_units must be greater than zero".to_owned());
        }
        if fixed_commitments_cents < 0 {
            return Err("fixed_commitments_cents must be non-negative".to_owned());
        }
        let sweep_total = u16::from(reserve_sweep_pct) + u16::from(investing_sweep_pct);
        if sweep_total > 100 {
            return Err(format!(
                "reserve_sweep_pct + investing_sweep_pct must be <= 100, got {sweep_total}"
            ));
        }

        Ok(Self {
            quarterly_units,
            days_to_vest,
            scenario_prices,
            fixed_commitments_cents,
            reserve_sweep_pct,
            investing_sweep_pct,
        })
    }
}

/// A comprehensive financial roadmap for a month relying on volatile equity income.
///
/// Establishes the safe spending baseline using the worst-case (Bear) scenario
/// while forecasting upside behavior for standard and optimistic market conditions.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RsuBudgetPlan {
    month_key: String,
    conservative_budget_cents: i64,
    fixed_commitments_cents: i64,
    baseline_remaining_cents: i64,
    reserve_sweep_pct: u8,
    investing_sweep_pct: u8,
    scenarios: [ScenarioBudgetProjection; 3],
}

impl RsuBudgetPlan {
    /// The temporal identifier (e.g., `2024-01`) grounding this simulation in a specific
    /// calendar month for reporting and synchronization with the general ledger.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// assert_eq!(plan.month_key(), "2024-05");
    /// ```
    #[must_use]
    pub fn month_key(&self) -> &str {
        &self.month_key
    }

    /// The absolute ceiling for discretionary spending in the current month, determined
    /// strictly by the income generated in the Bear (worst-case) market scenario.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// assert_eq!(plan.conservative_budget_cents(), 7500_00);
    /// ```
    #[must_use]
    pub const fn conservative_budget_cents(&self) -> i64 {
        self.conservative_budget_cents
    }

    /// The non-negotiable outflows (e.g. rent, mortgage, insurance) that must be cleared
    /// before any discretionary spending or surplus distribution can occur.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// assert_eq!(plan.fixed_commitments_cents(), 8000_00);
    /// ```
    #[must_use]
    pub const fn fixed_commitments_cents(&self) -> i64 {
        self.fixed_commitments_cents
    }

    /// The remaining buffer within the conservative budget after fulfilling fixed commitments.
    /// A negative value here indicates the portfolio carries catastrophic downside risk.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 5000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// // Conservative budget ($7,500) - Fixed Commitments ($5,000) = $2,500
    /// assert_eq!(plan.baseline_remaining_cents(), 2500_00);
    /// ```
    #[must_use]
    pub const fn baseline_remaining_cents(&self) -> i64 {
        self.baseline_remaining_cents
    }

    /// The policy rate defining the fraction of variable surplus routed directly to emergency funds.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// assert_eq!(plan.reserve_sweep_pct(), 10);
    /// ```
    #[must_use]
    pub const fn reserve_sweep_pct(&self) -> u8 {
        self.reserve_sweep_pct
    }

    /// The policy rate defining the fraction of variable surplus routed directly to long-term investing.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// assert_eq!(plan.investing_sweep_pct(), 20);
    /// ```
    #[must_use]
    pub const fn investing_sweep_pct(&self) -> u8 {
        self.investing_sweep_pct
    }

    /// Extracts the specific behavior details mapping to the requested market scenario.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan, ScenarioKey};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// assert!(plan.scenario(ScenarioKey::Base).is_some());
    /// ```
    #[must_use]
    pub fn scenario(&self, key: ScenarioKey) -> Option<&ScenarioBudgetProjection> {
        self.scenarios
            .iter()
            .find(|scenario| scenario.scenario() == key)
    }

    /// Fast path to the worst-case scenario model, representing the baseline constraint
    /// that grounds the entire plan.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// assert_eq!(plan.bear().unwrap().surplus_cents(), 0); // Bear never has surplus by definition
    /// ```
    #[must_use]
    pub fn bear(&self) -> Option<&ScenarioBudgetProjection> {
        self.scenario(ScenarioKey::Bear)
    }

    /// Fast path to the expected, normative scenario model, representing the most likely outcome.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// assert_eq!(plan.base().unwrap().monthly_income_cents(), 11250_00);
    /// ```
    #[must_use]
    pub fn base(&self) -> Option<&ScenarioBudgetProjection> {
        self.scenario(ScenarioKey::Base)
    }

    /// Fast path to the optimistic scenario model, demonstrating the upside velocity
    /// in high-growth market climates.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// assert_eq!(plan.bull().unwrap().monthly_income_cents(), 15000_00);
    /// ```
    #[must_use]
    pub fn bull(&self) -> Option<&ScenarioBudgetProjection> {
        self.scenario(ScenarioKey::Bull)
    }

    /// Provides access to the contiguous array of all generated scenario models for iteration.
    ///
    /// ## Examples
    ///
    /// ```
    /// use logos_reporting::{RsuBudgetPlanInput, ScenarioPriceInputs, project_rsu_budget_plan};
    ///
    /// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
    /// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
    /// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
    ///
    /// assert_eq!(plan.scenarios().len(), 3);
    /// ```
    #[must_use]
    pub const fn scenarios(&self) -> &[ScenarioBudgetProjection; 3] {
        &self.scenarios
    }
}

/// Projects a scenario-based RSU monthly budget model that uses bear-case income as baseline.
///
/// # Errors
///
/// Returns an error when the month key is empty.
///
/// ## Examples
///
/// ```
/// use logos_reporting::{project_rsu_budget_plan, RsuBudgetPlanInput, ScenarioPriceInputs};
///
/// let prices = ScenarioPriceInputs::new(100_00, 150_00, 200_00).unwrap();
/// let input = RsuBudgetPlanInput::new(300, 0, prices, 8000_00, 10, 20).unwrap();
///
/// let plan = project_rsu_budget_plan("2024-05", &input).unwrap();
///
/// // Note: Real calculation includes haircut/tax withholding (often ~25-40%).
/// // With the default ~25% haircut, $30,000 gross -> $22,500 net -> $7,500/mo.
/// assert_eq!(plan.conservative_budget_cents(), 7500_00);
///
/// // Base case price: $150.00 * 300 units = $45,000 gross. With 25% haircut = $33,750 net = $11,250/mo.
/// let base_scenario = plan.base().unwrap();
/// assert_eq!(base_scenario.monthly_income_cents(), 11250_00);
///
/// // Surplus = $11,250 (Base) - $7,500 (Conservative) = $3,750
/// assert_eq!(base_scenario.surplus_cents(), 3750_00);
/// ```
pub fn project_rsu_budget_plan(
    month_key: &str,
    input: &RsuBudgetPlanInput,
) -> Result<RsuBudgetPlan, String> {
    if month_key.is_empty() {
        return Err("month_key must not be empty".to_owned());
    }

    let tiers = HaircutTierTable::default();
    let bear_monthly = monthly_income(
        input.scenario_prices.bear,
        input.quarterly_units,
        input.days_to_vest,
        tiers,
    );
    let base_monthly = monthly_income(
        input.scenario_prices.base,
        input.quarterly_units,
        input.days_to_vest,
        tiers,
    );
    let bull_monthly = monthly_income(
        input.scenario_prices.bull,
        input.quarterly_units,
        input.days_to_vest,
        tiers,
    );

    let conservative_budget_cents = bear_monthly;
    let baseline_remaining_cents = conservative_budget_cents
        .saturating_sub(input.fixed_commitments_cents)
        .max(0);

    Ok(RsuBudgetPlan {
        month_key: month_key.to_owned(),
        conservative_budget_cents,
        fixed_commitments_cents: input.fixed_commitments_cents,
        baseline_remaining_cents,
        reserve_sweep_pct: input.reserve_sweep_pct,
        investing_sweep_pct: input.investing_sweep_pct,
        scenarios: [
            scenario_projection(
                ScenarioKey::Bear,
                bear_monthly,
                conservative_budget_cents,
                input.reserve_sweep_pct,
                input.investing_sweep_pct,
            ),
            scenario_projection(
                ScenarioKey::Base,
                base_monthly,
                conservative_budget_cents,
                input.reserve_sweep_pct,
                input.investing_sweep_pct,
            ),
            scenario_projection(
                ScenarioKey::Bull,
                bull_monthly,
                conservative_budget_cents,
                input.reserve_sweep_pct,
                input.investing_sweep_pct,
            ),
        ],
    })
}

fn monthly_income(price_cents: i64, units: u32, days_to_vest: u16, tiers: HaircutTierTable) -> i64 {
    let quarterly = forecast_value_cents(price_cents, units, days_to_vest, &tiers);
    quarterly / 3
}

fn scenario_projection(
    scenario: ScenarioKey,
    monthly_income_cents: i64,
    conservative_budget_cents: i64,
    reserve_sweep_pct: u8,
    investing_sweep_pct: u8,
) -> ScenarioBudgetProjection {
    let surplus_cents = monthly_income_cents
        .saturating_sub(conservative_budget_cents)
        .max(0);
    let reserve_sweep_cents = surplus_cents.saturating_mul(i64::from(reserve_sweep_pct)) / 100;
    let investing_sweep_cents = surplus_cents.saturating_mul(i64::from(investing_sweep_pct)) / 100;
    let available_after_sweeps_cents = monthly_income_cents
        .saturating_sub(reserve_sweep_cents)
        .saturating_sub(investing_sweep_cents);

    ScenarioBudgetProjection {
        scenario,
        monthly_income_cents,
        surplus_cents,
        reserve_sweep_cents,
        investing_sweep_cents,
        available_after_sweeps_cents,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_scenario_budget_projection_accessors() {
        let proj = ScenarioBudgetProjection {
            scenario: ScenarioKey::Base,
            monthly_income_cents: 100,
            surplus_cents: 200,
            reserve_sweep_cents: 300,
            investing_sweep_cents: 400,
            available_after_sweeps_cents: 500,
        };
        assert_eq!(proj.scenario(), ScenarioKey::Base);
        assert_eq!(proj.monthly_income_cents(), 100);
        assert_eq!(proj.surplus_cents(), 200);
        assert_eq!(proj.reserve_sweep_cents(), 300);
        assert_eq!(proj.investing_sweep_cents(), 400);
        assert_eq!(proj.available_after_sweeps_cents(), 500);
    }

    #[test]
    fn test_rsu_budget_plan_accessors() {
        let bear_proj = ScenarioBudgetProjection {
            scenario: ScenarioKey::Bear,
            monthly_income_cents: 0,
            surplus_cents: 0,
            reserve_sweep_cents: 0,
            investing_sweep_cents: 0,
            available_after_sweeps_cents: 0,
        };
        let base_proj = ScenarioBudgetProjection {
            scenario: ScenarioKey::Base,
            ..bear_proj
        };
        let bull_proj = ScenarioBudgetProjection {
            scenario: ScenarioKey::Bull,
            ..bear_proj
        };

        let plan = RsuBudgetPlan {
            month_key: "2024-01".to_owned(),
            conservative_budget_cents: 10,
            fixed_commitments_cents: 20,
            baseline_remaining_cents: 30,
            reserve_sweep_pct: 40,
            investing_sweep_pct: 50,
            scenarios: [bear_proj, base_proj, bull_proj],
        };

        assert_eq!(plan.month_key(), "2024-01");
        assert_eq!(plan.conservative_budget_cents(), 10);
        assert_eq!(plan.fixed_commitments_cents(), 20);
        assert_eq!(plan.baseline_remaining_cents(), 30);
        assert_eq!(plan.reserve_sweep_pct(), 40);
        assert_eq!(plan.investing_sweep_pct(), 50);

        assert_eq!(
            plan.scenario(ScenarioKey::Bear)
                .expect("should succeed")
                .scenario(),
            ScenarioKey::Bear
        );
        assert_eq!(
            plan.bear().expect("should succeed").scenario(),
            ScenarioKey::Bear
        );
        assert_eq!(
            plan.base().expect("should succeed").scenario(),
            ScenarioKey::Base
        );
        assert_eq!(
            plan.bull().expect("should succeed").scenario(),
            ScenarioKey::Bull
        );

        let sc = plan.scenarios();
        assert_eq!(sc.len(), 3);
        assert_eq!(sc[0].scenario(), ScenarioKey::Bear);
    }

    #[test]
    fn test_scenario_projection_sweeps() {
        let proj = scenario_projection(
            ScenarioKey::Base,
            1000,
            200, // surplus = 800
            10,  // 10% = 80
            20,  // 20% = 160
        );
        assert_eq!(proj.surplus_cents(), 800);
        assert_eq!(proj.reserve_sweep_cents(), 80);
        assert_eq!(proj.investing_sweep_cents(), 160);
        assert_eq!(proj.available_after_sweeps_cents(), 1000 - 80 - 160); // 760
    }

    #[test]
    fn test_monthly_income_math() {
        let tiers = HaircutTierTable::default();
        let val = monthly_income(1000, 300, 0, tiers);
        assert_eq!(val, 75000);
    }

    #[test]
    fn test_project_rsu_budget_plan() {
        let prices = ScenarioPriceInputs::new(100, 200, 300).expect("should succeed");
        let input = RsuBudgetPlanInput::new(300, 0, prices, 5000, 10, 20).expect("should succeed");

        let plan = project_rsu_budget_plan("2024-01", &input).expect("should succeed");

        assert_eq!(plan.conservative_budget_cents(), 7500);
        assert_eq!(plan.baseline_remaining_cents(), 7500 - 5000); // 2500
    }

    #[test]
    fn test_scenario_price_inputs_validation_errors() {
        assert_eq!(
            ScenarioPriceInputs::new(0, 200, 300).unwrap_err(),
            "scenario prices must be positive"
        );
        assert_eq!(
            ScenarioPriceInputs::new(100, -200, 300).unwrap_err(),
            "scenario prices must be positive"
        );
        assert_eq!(
            ScenarioPriceInputs::new(100, 200, 0).unwrap_err(),
            "scenario prices must be positive"
        );
        assert_eq!(
            ScenarioPriceInputs::new(300, 200, 100).unwrap_err(),
            "scenario prices must satisfy bear <= base <= bull"
        );
        assert_eq!(
            ScenarioPriceInputs::new(100, 300, 200).unwrap_err(),
            "scenario prices must satisfy bear <= base <= bull"
        );
    }

    #[test]
    fn test_rsu_budget_plan_input_validation_errors() {
        let valid_prices = ScenarioPriceInputs::new(100, 200, 300).expect("should succeed");

        assert_eq!(
            RsuBudgetPlanInput::new(0, 10, valid_prices, 5000, 10, 20).unwrap_err(),
            "quarterly_units must be greater than zero"
        );

        assert_eq!(
            RsuBudgetPlanInput::new(100, 10, valid_prices, -5000, 10, 20).unwrap_err(),
            "fixed_commitments_cents must be non-negative"
        );

        assert_eq!(
            RsuBudgetPlanInput::new(100, 10, valid_prices, 5000, 60, 50).unwrap_err(),
            "reserve_sweep_pct + investing_sweep_pct must be <= 100, got 110"
        );
    }
    #[test]
    fn project_rsu_budget_plan_saturates_on_overflow() {
        let prices = ScenarioPriceInputs::new(100, 200, 300).expect("should succeed");
        let input =
            RsuBudgetPlanInput::new(300, 0, prices, i64::MAX, 10, 20).expect("should succeed");

        let plan = project_rsu_budget_plan("2024-01", &input).expect("should succeed");
        assert_eq!(plan.baseline_remaining_cents(), 0);
    }

    #[test]
    fn test_monthly_income_divide_by_three() {
        let tiers = HaircutTierTable::default();
        let val = monthly_income(1000, 300, 0, tiers);
        // With default 25% haircut: 1000 cents * 300 units = 300000 cents.
        // Haircut 25% leaves 225000 cents.
        // / 3 months = 75000 cents.
        assert_eq!(val, 75000);

        // Ensure that replacing `/ 3` with `% 3` or `* 3` fails the test.
        // * 3 = 675000
        // % 3 = 0
        // This assertion naturally covers it.
    }

    #[test]
    fn test_scenario_projection_sweeps_math() {
        let proj = scenario_projection(
            ScenarioKey::Base,
            10000, // monthly_income_cents
            5000,  // conservative_budget_cents
            10,    // reserve_sweep_pct
            20,    // investing_sweep_pct
        );

        // Surplus = 10000 - 5000 = 5000
        assert_eq!(proj.surplus_cents, 5000);

        // Reserve sweep = 5000 * 10 / 100 = 500
        assert_eq!(proj.reserve_sweep_cents, 500);

        // Investing sweep = 5000 * 20 / 100 = 1000
        assert_eq!(proj.investing_sweep_cents, 1000);

        // Available after sweeps = 10000 - 500 - 1000 = 8500
        assert_eq!(proj.available_after_sweeps_cents, 8500);

        // The assertions naturally kill `/ 100` -> `% 100` mutants.
    }
}
