[package]
name = "logos-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
blake3 = "1.8.3"
chrono = { version = "0.4.42", default-features = true, features = ["clock"] }
logos-core = { path = "../logos-core" }
logos-fetch = { path = "../logos-fetch" }
logos-import = { path = "../logos-import" }
logos-reporting = { path = "../logos-reporting" }
logos-store = { path = "../logos-store" }
logos-store-pg = { path = "../logos-store-pg" }
polars = { version = "0.46.0", features = ["parquet"] }
tokio = { version = "1.48.0", features = ["rt"] }

[dev-dependencies]
proptest = "1.5"
