[package]
name = "logos-store-pg"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
diesel = { version = "2", features = ["postgres"] }
diesel_migrations = "2"
logos-store = { path = "../logos-store" }
pq-sys = { version = "0.7", features = ["bundled_without_openssl"] }
thiserror = "2.0.18"

[dev-dependencies]
logos-core = { path = "../logos-core" }
